// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/demeero/pocket-link/proto/gen/go/pocketlink/keygen/v1beta1 (interfaces: KeygenServiceClient)

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	v1beta1 "github.com/demeero/pocket-link/proto/gen/go/pocketlink/keygen/v1beta1"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockKeygenServiceClient is a mock of KeygenServiceClient interface.
type MockKeygenServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockKeygenServiceClientMockRecorder
}

// MockKeygenServiceClientMockRecorder is the mock recorder for MockKeygenServiceClient.
type MockKeygenServiceClientMockRecorder struct {
	mock *MockKeygenServiceClient
}

// NewMockKeygenServiceClient creates a new mock instance.
func NewMockKeygenServiceClient(ctrl *gomock.Controller) *MockKeygenServiceClient {
	mock := &MockKeygenServiceClient{ctrl: ctrl}
	mock.recorder = &MockKeygenServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeygenServiceClient) EXPECT() *MockKeygenServiceClientMockRecorder {
	return m.recorder
}

// GenerateKey mocks base method.
func (m *MockKeygenServiceClient) GenerateKey(arg0 context.Context, arg1 *v1beta1.GenerateKeyRequest, arg2 ...grpc.CallOption) (*v1beta1.GenerateKeyResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GenerateKey", varargs...)
	ret0, _ := ret[0].(*v1beta1.GenerateKeyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateKey indicates an expected call of GenerateKey.
func (mr *MockKeygenServiceClientMockRecorder) GenerateKey(arg0, arg1 interface{}, arg2 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateKey", reflect.TypeOf((*MockKeygenServiceClient)(nil).GenerateKey), varargs...)
}
