version: "3.9"
services:

  keygen:
    networks:
      - pocket-link
    build:
      context: ./keygen
      args:
        ssh_key:
    environment:
      - GENERATOR_PREDEFINEDKEYSCOUNT=100
      - GENERATOR_DELAY=1s
      - GENERATOR_KEYLEN=8
      - GRPC_PORT=8081
      - REDISUNUSEDKEYS_ADDR=redis-keygen:6379
      - REDISUNUSEDKEYS_DB=1
#      - REDISUSEDKEYS_ADDR=redis-keygen:6379
#      - REDISUSEDKEYS_DB=2
      - MONGOUSEDKEYS_URI=mongodb://mongo-links:27017
      - USEDKEYSREPOSITORYTYPE=mongo
      - KEYS_TTL=1h
    ports:
      - "8084:8081"
    expose:
      - "8081"

  links:
    networks:
      - pocket-link
    build:
      context: ./links
      args:
        ssh_key:
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=8081
      - KEYGEN_ADDR=keygen:8081
      - MONGO_URI=mongodb://mongo-links:27017
    ports:
      - "8085:8080"
      - "8086:8081"
    expose:
      - "8080"
      - "8081"

  redirects:
    networks:
      - pocket-link
    build:
      context: ./redirects
      args:
        ssh_key:
    environment:
      - HTTP_PORT=8080
      - LINKS_ADDR=links:8081
      - REDISLRU_ADDR=redis-lru:6380
    ports:
      - "8087:8080"
    expose:
      - "8080"

networks:
  pocket-link:
    driver: bridge