version: "3.9"
services:

  keygen:
    build:
      context: ./keygen
    environment:
      - TELEMETRY_COLLECTOR_ADDR=otel-collector:55681
      - GENERATOR_PREDEFINED_KEYS_COUNT=100
      - GENERATOR_DELAY=1s
      - GENERATOR_KEYLEN=8
      - GRPC_PORT=8081
      - REDIS_UNUSED_KEYS_ADDR=redis-keygen:6379
      - REDIS_UNUSED_KEYS_DB=1
      #      - REDISUSEDKEYS_ADDR=redis-keygen:6379
      #      - REDISUSEDKEYS_DB=2
      - MONGO_USED_KEYS_URI=mongodb://mongo-links:27017
      - USED_KEYS_REPOSITORY_TYPE=mongo
      - KEYS_TTL=1h
    ports:
      - "8084:8081"
    expose:
      - "8081"

  links:
    build:
      context: ./links
    environment:
      - TELEMETRY_COLLECTOR_ADDR=otel-collector:55681
      - HTTP_PORT=8080
      - GRPC_PORT=8081
      - KEYGEN_ADDR=keygen:8081
      - MONGO_URI=mongodb://mongo-links:27017
    ports:
      - "8085:8080"
      - "8086:8081"
    expose:
      - "8080"
      - "8081"

  redirects:
    build:
      context: ./redirects
    environment:
      - TELEMETRY_COLLECTOR_ADDR=otel-collector:55681
      - HTTP_PORT=8080
      - LINKS_ADDR=links:8081
      - REDISLRU_ADDR=redis-lru:6380
    ports:
      - "8087:8080"
    expose:
      - "8080"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8088:80"
    expose:
      - "80"

networks:
  default:
    name: pocket-link
