version: "3.9"
services:

  redis-keygen:
    networks:
      - pocket-link
    image: redis:6.0.9-alpine3.12
    restart: always
    ports:
      - 6479:6379

  mongo-links:
    networks:
      - pocket-link
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-links-data:/data/db

  mongo-express-links:
    networks:
      - pocket-link
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-links

volumes:
  mongo-links-data:

networks:
  pocket-link:
    driver: bridge