version: "3.9"
services:

  keygen:
    build:
      context: ./keygen
    env_file:
      - keygen.env
    ports:
      - "8080:8080"

  links:
    build:
      context: ./links
    env_file:
      - links.env
    ports:
      - "8081:8080"
      - "8082:8081"

  redirects:
    build:
      context: ./redirects
    env_file:
      - redirects.env
    ports:
      - "8083:8080"

  frontend:
    image: demeero/pocket-link-frontend
    ports:
      - "8084:80"

  jaeger:
    image: jaegertracing/all-in-one:1.43
    expose:
      - "16686"
      - "14250"
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:0.75.0
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    expose:
      - "4317" # OTLP GRPC receiver
      - "8889" # Prometheus exporter metrics
      - "16686" # Dashboard
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  redis:
    image: redis:7-alpine3.17
    ports:
      - "6479:6379"

  redis-lru:
    image: redis:7-alpine3.17
    command: [ "--port 6380", "--maxmemory 2mb", "--maxmemory-policy allkeys-lru" ]
    ports:
      - "6480:6380"

  mongo:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
