version: "3.9"
services:

  keygen:
    build:
      context: ./keygen
      args:
        ssh_key:
    environment:
      - GENERATOR_PREDEFINEDKEYSCOUNT=100
      - GENERATOR_DELAY=1s
      - GENERATOR_KEYLEN=8
      - GRPC_PORT=8081
      - REDISUNUSEDKEYS_ADDR=redis-keygen:6379
      - REDISUNUSEDKEYS_DB=1
      - REDISUSEDKEYS_ADDR=redis-keygen:6379
      - REDISUSEDKEYS_DB=2
      - KEYS_TTL=1h
    ports:
      - "8084:8081"
    expose:
      - "8081"

  links:
    build:
      context: ./links
      args:
        ssh_key:
    environment:
      - HTTP_PORT=8080
      - GRPC_PORT=8081
      - KEYGEN_ADDR=keygen:8081
      - MONGO_URI=mongodb://mongo-links:27017
    ports:
      - "8085:8080"
      - "8086:8081"
    expose:
      - "8080"
      - "8081"

  redirects:
    build:
      context: ./redirects
      args:
        ssh_key:
    environment:
      - HTTP_PORT=8080
      - LINKS_ADDR=links:8081
    ports:
      - "8087:8080"
    expose:
      - "8080"

  redis-keygen:
    image: redis:6.0.9-alpine3.12
    restart: always
    ports:
      - 6479:6379

  mongo-links:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-links-data:/data/db

  mongo-express-links:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-links

volumes:
  mongo-links-data: