receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  jaeger:
    endpoint: jaeger:14250
    insecure: true
  logging:
    loglevel: DEBUG

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      exporters: [ jaeger ]
      processors: [ batch ]
