version: "3.9"
services:

  links:
    build:
      dockerfile: dev.Dockerfile
    container_name: links
    volumes:
      - ./:/workdir
    ports:
      - "8081:8081"
      - "8082:8080"

  mongo:
    container_name: mongo-links
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-links-data:/data/db

volumes:
  mongo-links-data:
