apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pocket-link

resources:
  - keygen.yaml
  - links.yaml
  - redirects.yaml
  - frontend.yaml

# these labels will be automatically included in label selectors
commonLabels:
  app.kubernetes.io/part-of: pocket-link

# adding labels without also automatically injecting corresponding selectors
labels:
  - pairs:
      app.kubernetes.io/version: latest # will be overriden by replacement below
      promtail.scrape: "true"
    includeTemplates: true
    includeSelectors: false

configMapGenerator:
  - name: keygen
    envs:
      - keygen.env
  - name: links
    envs:
      - links.env
  - name: redirects
    envs:
      - redirects.env
  - name: nginx-html
    files:
      - ../../frontend/index.html
  - name: nginx-conf
    files:
      - nginx.conf

replacements:
  - source:
      kind: Deployment
      name: keygen
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: keygen
        fieldPaths:
          - spec.template.metadata.labels.[app.kubernetes.io/version]
  - source:
      kind: Deployment
      name: links
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: links
        fieldPaths:
          - spec.template.metadata.labels.[app.kubernetes.io/version]
  - source:
      kind: Deployment
      name: redirects
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
    targets:
      - select:
          kind: Deployment
          name: redirects
        fieldPaths:
          - spec.template.metadata.labels.[app.kubernetes.io/version]
