version: "3.9"
services:

  jaeger:
    image: jaegertracing/all-in-one:1.22.0
    expose:
      - "16686"
      - "14250"
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector:0.23.0
    command: [ "--config=/etc/otel-collector-config.yaml", "--log-level=info" ]
    expose:
      - "55681" # HTTP otel receiver
      - "8889" # Prometheus exporter metrics
      - "16686" # Dashboard
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml

  redis-keygen:
    image: redis:6.0.9-alpine3.12
    restart: always
    ports:
      - 6479:6379

  redis-lru:
    image: redis:6.0.9-alpine3.12
    restart: always
    command: [ "--port 6380", "--maxmemory 2mb", "--maxmemory-policy allkeys-lru" ]
    ports:
      - 6480:6380

  mongo-links:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-links-data:/data/db

  mongo-express-links:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-links

volumes:
  mongo-links-data:

networks:
  default:
    name: pocket-link